package com.example.spring.controller;

import com.example.spring.CORSFilter;
import com.example.spring.model.Book;
import com.example.spring.model.Feedback;
import com.example.spring.model.User;
import com.example.spring.repository.BookRepository;
import com.example.spring.repository.FeedbackRepository;
import com.example.spring.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/bookabook") // This means URL's start with /demo (after Application path)
public class FeedbackController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FeedbackRepository feedbackRepository;

    @Autowired
    private UserRepository userRepository;


    @PostMapping(path = "/addfeedback")
    @CrossOrigin(origins = "http://localhost:4200")
    public @ResponseBody void addFeedback(@RequestBody Feedback feedback) {//CORS
        feedbackRepository.save(feedback);
    }

    @GetMapping(path = "/getfeedback", params = "bookID")
    @CrossOrigin(origins = "http://localhost:4200")
    public @ResponseBody Iterable<Feedback> getFeedback(@RequestParam(value = "bookID") int bookID) {
        System.out.println("get list of feedback");
        return feedbackRepository.findAllByBookID(bookID);
    }
}
